{% set name = "fpdf2" %}
{% set version = "2.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fpdf2-{{ version }}.tar.gz
  sha256: 494dc0bd935271c9ce16fb3a47c98b6f59b8d160cd519c2d3a7ed243c3852456

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - defusedxml
    - fonttools >=4.34.0
    - pillow >=6.2.2,!=9.2.*
    - python >={{ python_min }}

test:
  imports:
    - fpdf
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pyfpdf.github.io/fpdf2/
  dev_url: https://github.com/PyFPDF/fpdf2
  summary: Simple PDF generation for Python
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/rpaframework-core
    - thewchan
