{% set name = "fpdf2" %}
{% set version = "2.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fpdf2-{{ version }}.tar.gz
  sha256: 5e53fd440b1b6dc24a33f5c12d05bc349f923a78f50e2ecb2f0b876b55182c41

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<4.0
  run:
    - defusedxml
    - fonttools >=4.34.0
    - pillow >=6.2.2
    - python >=3.7,<4.0

test:
  imports:
    - fpdf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pyfpdf.github.io/fpdf2/
  dev_url: https://github.com/PyFPDF/fpdf2
  summary: Simple PDF generation for Python
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/rpaframework-core
    - thewchan
