{% set name = "fpdf2" %}
{% set version = "2.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fpdf2-{{ version }}.tar.gz
  sha256: adf41d085f39fc3f18e000d5cc9d659e6dae093bf8a202afc87df6e03d7e2555

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
  run:
    - pillow
    - python >=3.6,<4.0
    - defusedxml >=0.7.0,<0.8.0

test:
  imports:
    - fpdf
    - fpdf.util
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pyfpdf.github.io/fpdf2/
  summary: Simple PDF generation for Python
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/rpaframework-core
