schema_version: 1

context:
  name: fpdf2
  version: 2.8.4

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/fpdf2-${{ version }}.tar.gz
  sha256: 12b1f1dd35d0c2f35284bcfe10b153d6ca4baf29377379843e73d3f971eab6b7

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - defusedxml
    - fonttools >=4.34.0
    - pillow >=8.0.0,!=9.2.*
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - fpdf
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Simple PDF generation for Python
  license: LGPL-3.0-or-later
  license_file: LICENSE
  homepage: https://pyfpdf.github.io/fpdf2/
  repository: https://github.com/PyFPDF/fpdf2

extra:
  recipe-maintainers:
    - conda-forge/rpaframework-core
    - thewchan
