schema_version: 1

context:
  name: fpdf2
  version: "2.8.9"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/fpdf2-${{ version }}.tar.gz
  sha256: 5b0b3786f5236a2b3cc83c1fee567df17ddd314f8c4e13d820d8f09b617ab4f0

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=61.0
    - wheel
    - fonttools
  run:
    - defusedxml
    - fonttools >=4.34.0
    - pillow >=8.3.2,!=9.2.*
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - fpdf
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Simple PDF generation for Python
  license: LGPL-3.0-or-later
  license_file: LICENSE
  homepage: https://pyfpdf.github.io/fpdf2/
  repository: https://github.com/PyFPDF/fpdf2

extra:
  recipe-maintainers:
    - conda-forge/rpaframework-core
    - thewchan
