schema_version: 1

context:
  name: fpdf2
  version: "2.8.6"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/fpdf2-${{ version }}.tar.gz
  sha256: 5132f26bbeee69a7ca6a292e4da1eb3241147b5aea9348b35e780ecd02bf5fc2

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=61.0
    - wheel
    - fonttools
  run:
    - defusedxml
    - fonttools >=4.34.0
    - pillow >=8.0.0,!=9.2.*
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - fpdf
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Simple PDF generation for Python
  license: LGPL-3.0-or-later
  license_file: LICENSE
  homepage: https://pyfpdf.github.io/fpdf2/
  repository: https://github.com/PyFPDF/fpdf2

extra:
  recipe-maintainers:
    - conda-forge/rpaframework-core
    - thewchan
